substitutions:
  _PROJECT_ID: affable-beaker-407007

options:
  dynamic_substitutions: true
steps:
  # Step 1: Use an official Node.js image for installing dependencies
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Use the same Node.js image for building the React app
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
        ls -lha
        cd build
        pwd
        ls -lha

   # Step 2: Install Ansible
  - name: 'python:3.8'
    entrypoint: 'pip'
    args: ['install', 'ansible']

   # Step 3: Run Ansible playbook to transfer build files to GCP VM
  - name: 'https://hub.docker.com/r/webdevops/ansible' 
    args:
      - 'ansible-playbook'
      - '-i'
      - '/workspace/inventory.ini'
      - '/workspace/deploy.yml'    
      
