steps:
  # Step 1: Use an official Node.js image for installing dependencies
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Use the same Node.js image for building the React app
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'build']
