# deploy.yml
- name: SSH into GCP VM using Ansible playbook
  hosts: all
  gather_facts: no
  tasks:
  - name: Authenticate with GCP
    gcp_compute_auth:
      credentials_file: /path/to/credentials.json
  - name: SSH into Compute Engine VM
    ssh:
      user: niteshshewale6
      host: 34.93.111.35
      key_file: /workspace/private_key

