# deploy.yml

---
- name: Exchange Keys between servers
  hosts: instance-1
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"  

    - name: Deploy SSH Key
      authorized_key: user={{username}}
                     key="{{ lookup('file', 'id_rsa.pub') }}"
                     state=present    
