# deploy.yml

---
- name: Exchange Keys between servers
  hosts: instance-1
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: copy the keyfile from the node to master
      tags: run
      fetch: 
        csrc: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{instance-1}}-id_rsa.pub"
        flat: yes

     - name: Copy SSh Key | copying shh key to remote host
       authorized_key:
          user: "<your_user>"
          state: present
          key: "{{ lookup('file', item) }}"
       with_fileglob:
       - id_rsa.pub
       become: true
