# deploy.yml

---
# - name: Exchange Keys between servers
-  hosts: all
   become: true
   become_user: root
   gather_facts: false
   vars:
    username: "niteshshewale6"

   tasks:
    
      #- name: SSH KeyGen command
      #  tags: run
      #  shell: > 
      #   ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
      #   creates="~/.ssh/id_rsa"  

      - name: Deploy SSH Key
        authorized_key: user="{{username}}"
               key="{{ lookup('file', 'id_rsa')}}"
               state=present 
     
      - name: Add a new user named devops
        user:
          name={{username}}
          password={{ ansible }}
 
      - name: Add devops user to the sudoers
        copy:
          dest: "/etc/sudoers.d/{{username}}"
          content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"
    
    

       
