# deploy.yml

---
- name: Deploy React App on GCP VM
  hosts: instance-1
  gather_facts: yes
  become: yes 
  connection: ssh
  tasks:
    - name: deploy to server
      command: sudo apt update -y
      #copy:
       # src: '/workspace/build'
       # dest: '/var/www/html'
