# deploy.yml

---
- name: Deploy React App on GCP VM
  hosts: 34.93.111.35
  gather_facts: false
  become: yes 
  tasks:
    - name: run a command
      command: sudo apt update -y

     # copy:
      #  src: '/workspace/build'
       # dest: '/var/www/html'
