# deploy.yml

---
- name: Deploy React App on GCP VM
  hosts: 34.100.224.118
  gather_facts: false
  become: yes 
  tasks:
    - name: deploy to server
      command: sudo apt update -y
      #copy:
       # src: '/workspace/build'
       # dest: '/var/www/html'
