# deploy.yml

---
- name: Exchange Keys between servers
  hosts: instance-1
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    
    - name: Copy SSh Key | copying shh key to remote host
       authorized_key:
          user: "root"
          state: present
          key: "{{ lookup('file','id_rsa.pub) }}"
       with_fileglob:
       - id_rsa.pub 
       become: true
