name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Running tests
        run: npm run test
